# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "live.ddev.composer"
version = "0.0.1"
name = "Composer Buildpack"

[[stacks]]
id = "live.ddev.stacks.7.3"
[[stacks]]
id = "live.ddev.stacks.7.2"
